### PR TITLE
create scan_instance_view + ppdd_analytics_user

### PR DESCRIPTION
**Pull request by hilmarf**

### CODE REVIEW

**Comment by DKOVACS5** [comment]
Seems fine for me, not sure do we need to use the prefix public Shema for the grant select view for the scan_instance_view but my guess is no

**Review by DKOVACS5 — APPROVED** [review]
Seems okay

**Review by DKOVACS5 — APPROVED** [review]

**Review by DKOVACS5 — CHANGES_REQUESTED** [review]
I think the DROP view is not necessary because if exists then will be replaced.

The grant select view using the public schema instead of the data_donation but I believe it will work without prefix so I suggest using the GRANT SELECT ON view scan_instance_view TO ppdd_analytics_user, and if some issue will appear with that I will change that to public.scan_instance_view. 

The grant select view can be in the user creation script but in this case, the view should create first and then the user. If we keep the grant select in the view creation script then we can create the roles and user first.

**Comment by hilmarf** [comment]
> If we keep the grant select in the view creation script then we can create the roles and user first.

doesn't work with the circleci build (see https://app.circleci.com/pipelines/github/corona-warn-app/cwa-ppa-server/1327/workflows/052ba2a7-6cdd-42ae-adcf-72feecdeb358), as it tries to execute the migration, but doesn't know anything about the different users + roles... that's why I moved it

**Comment by DKOVACS5** [comment]
> > If we keep the grant select in the view creation script then we can create the roles and user first.
> 
> @DKOVACS5
> doesn't work with the circleci build (see https://app.circleci.com/pipelines/github/corona-warn-app/cwa-ppa-server/1327/workflows/052ba2a7-6cdd-42ae-adcf-72feecdeb358), as it tries to execute the migration, but doesn't know anything about the different users + roles... that's why I moved it

I see, may I suggest trying like this GRANT SELECT ON view public.scan_instance_view TO ppdd_analytics_user;
But if it is working with the new version it is fine for me but I will be surprised if the scan_instance_view use the data_donation Shema

**Review by DKOVACS5 — APPROVED** [review]

**Review by FelixRottler — APPROVED** [review]

**Review by AliceBilc — APPROVED** [review]

**Pull request merged**
