### PR TITLE
Link to repository table in documentation repository (README change only)

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR discontinues the [repository table](https://github.com/corona-warn-app/cwa-ppa-server#repositories) in the README here, instead the README now links to the [table](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md#repositories) in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation).
This will make it easier to update the list with newly created repositories.

### CODE REVIEW

**Review by hilmarf — APPROVED** [review]

**Comment by MikeMcC399** [comment]
Have you considered keeping one list of repositories in a central place, for example using the [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) repository and then linking to the [repository table](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md#repositories) using `https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md#repositories`?

This would be instead of having to edit an identical list in all 12 repositories every time something changes.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Good idea, @hilmarf should I implement that?

**Comment by hilmarf** [comment]
@Ein-Tim, sure - yes please!

**Review by dsarkar — APPROVED** [review]

**Review by dsarkar — APPROVED** [review]

**Review by hilmarf — APPROVED** [review]

**Comment by hilmarf** [comment]
Hi @EugenM-SAP, 
can you please have another look on the failing test?
```
[ERROR] Tests run: 21, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.546 s <<< FAILURE! - in app.coronawarn.datadonation.services.ppac.android.controller.AndroidControllerTest$AttestationVerification
[ERROR] app.coronawarn.datadonation.services.ppac.android.controller.AndroidControllerTest$AttestationVerification.checkResponseStatusForValidNonce  Time elapsed: 0.069 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <403 FORBIDDEN>
to be equal to:
 <204 NO_CONTENT>
but was not.
```
https://app.circleci.com/pipelines/github/corona-warn-app/cwa-ppa-server/808/workflows/c904f5bd-0722-45b5-a527-56e2cdcb7247/jobs/815

**Pull request merged**
